#!/bin/bash

HOME=".."
MODEL="../src/model"
SERVICES="../src/services"

echo -n "Generating the header-only file        ... "

LOCATION=${HOME}/single_include
mkdir -p "$LOCATION"
FILE="$LOCATION/graph.hpp"

cat > "$FILE" << EOF
/*
 *    ╔═╗╦═╗╔═╗╔═╗╦ ╦  C++ Graph library
 *    ║ ╦╠╦╝╠═╣╠═╝╠═╣  
 *    ╚═╝╩╚═╩ ╩╩  ╩ ╩  Version 1.1.1
 *
 *
 * Single header-file generated by $USER on $(date +%F)
 *
 *
 * Licensed under the MIT License <https://opensource.org/licenses/MIT>.
 * Copyright (c) 2018 Shawn
 *
 * Permission is hereby  granted, free of charge, to any  person obtaining a copy
 * of this software and associated  documentation files (the "Software"), to deal
 * in the Software  without restriction, including without  limitation the rights
 * to  use, copy,  modify, merge,  publish, distribute,  sublicense, and/or  sell
 * copies  of the Software,  and  to  permit persons  to  wholm  the Software  is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE  IS PROVIDED "AS  IS", WITHOUT WARRANTY  OF ANY KIND,  EXPRESS OR
 * IMPLIED,  INCLUDING BUT  NOT  LIMITED TO  THE  WARRANTIES OF  MERCHANTABILITY,
 * FITNESS FOR  A PARTICULAR PURPOSE AND  NONINFRINGEMENT. IN NO EVENT  SHALL THE
 * AUTHORS  OR COPYRIGHT  HOLDERS  BE  LIABLE FOR  ANY  CLAIM,  DAMAGES OR  OTHER
 * LIABILITY, WHETHER IN AN ACTION OF  CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE  OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

EOF

# Copying Graph.h, GraphSearch.h, Graph.cpp, Node.cpp and GraphSearch.cpp into graph.hpp
sed -e '/#include "Graph.cpp"/ {' -e "r ${SERVICES}/GraphSearch.h" -e "r ${MODEL}/Node.cpp" -e "r ${MODEL}/Graph.cpp" -e "r ${SERVICES}/GraphSearch.cpp" -e 'd' -e '}' ${MODEL}/Graph.h >> "$FILE" || exit 2
# Copying Node.h into graph.hpp
sed -i -e '/#include "Node.h"/ {' -e "r ${MODEL}/Node.h" -e 'd' -e '}' "$FILE" || exit 2
sed -i '/#include "Node.cpp"/,+2d' "$FILE" || exit 2
sed -i 's/#include "model\/Graph.h"//' "$FILE" || exit 2
sed -i 's/#include "GraphSearch.cpp"//' "$FILE" || exit 2
# Copying detail.hpp into graph.hpp
sed -i -e '/#include "detail.hpp"/ {' -e "r ${MODEL}/detail.hpp" -e 'd' -e '}' "$FILE" || exit 2
# Modifying #ifndef/#define values
sed -i 's/ROOT_GRAPH_H/ROOT_GRAPH_FINAL_H/' "$FILE" || exit 2
sed -i '/ROOT_NODE_H/d' "$FILE" || exit 2
sed -i '/ROOT_DETAIL_H/d' "$FILE" || exit 2
# Remove comments
sed -i 's/\/\/\/.*//' "$FILE" || exit 2
# Remove trailing whitespaces
sed -i 's/[ \t]*$//' "$FILE" || exit 2
# Remove unnecessary EOF
sed -i '/^$/N;/\n$/D' "$FILE" || exit 2
# Change '//!' into '//'
sed -i 's/\/\/!/\/\/\//' "$FILE" || exit 2

echo "Done."
